### PR TITLE
List View

### PR DESCRIPTION
**Pull request by Bad-At-Usernames**
Added a setting to view instances as a list instead of a grid. It's toggled by an option in the settings page. It's saved through the UI store.  This is also half a suggestion, **feel free to not accept this** if you don't want it!

### CODE REVIEW

**Comment by redcreeper14385** [comment]
Why did you close it?

**Comment by Suyashtnt** [comment]
yeah, this is a really good PR, lemme merge it and adjust it

**Comment by Bad-At-Usernames** [comment]
Forgot to lint it. I've fixed it now, may have to submit another one.

**Comment by Suyashtnt** [comment]
its already merged and finalized with linting :tiny_potato:

**Pull request merged**
