### PR TITLE
🇫🇷French Translation 🇫🇷

### PR DESCRIPTION
**Pull request by anatom3000**

### CODE REVIEW

**Comment by Suyashtnt** [comment]
shut the E up restyled

**Comment by Suyashtnt** [comment]
also your gonna need to add your translations in `src/renderer/nuxt.config.js`

**Comment by Suyashtnt** [comment]
added for you

**Comment by anatom3000** [comment]
Thanks :)

**Comment by anatom3000** [comment]
Done ! You can merge 👍

**Pull request merged**
